#!/usr/bin/env node
// Patch react-native-purchases/android/build.gradle to remove the buildscript
// block that declares AGP 8.11.1. This version of AGP is newer than what
// EAS build workers have cached, causing EAS_BUILD_UNKNOWN_GRADLE_ERROR.
// The library's own buildscript block is unnecessary in Expo managed workflow
// because the root project (generated by expo prebuild) already provides AGP.

const fs = require('fs');
const path = require('path');

const buildGradlePath = path.join(
  __dirname,
  '..',
  'node_modules',
  'react-native-purchases',
  'android',
  'build.gradle'
);

if (!fs.existsSync(buildGradlePath)) {
  console.log('react-native-purchases not found, skipping patch.');
  process.exit(0);
}

let content = fs.readFileSync(buildGradlePath, 'utf8');

// Only patch if the problematic buildscript block is present
if (!content.includes("classpath 'com.android.tools.build:gradle:")) {
  console.log('react-native-purchases/android/build.gradle already patched.');
  process.exit(0);
}

// Remove the entire buildscript { ... } block (including the kotlinVersion helper)
// The block spans from "buildscript {" to its closing "}"
const patchedContent = content.replace(
  /^buildscript \{[\s\S]*?\n\}\n/m,
  ''
);

if (patchedContent === content) {
  console.warn('WARNING: Could not find buildscript block to remove. Pattern may have changed.');
  process.exit(0);
}

fs.writeFileSync(buildGradlePath, patchedContent, 'utf8');
console.log('✅ Patched react-native-purchases/android/build.gradle (removed AGP 8.11.1 buildscript block)');
